/**
 * Languages in rough order of how often they turn up in documents. The picker
 * lists them in this order, then everything else alphabetically, so the common
 * choice is a glance away instead of a scroll away.
 */
const POPULAR_LANGUAGES = [
  'js',
  'ts',
  'tsx',
  'jsx',
  'py',
  'java',
  'go',
  'rs',
  'json',
  'html',
  'css',
  'scss',
  'bash',
  'sql',
  'yaml',
  'md',
  'php',
  'cs',
  'cpp',
  'c',
  'rb',
  'swift',
  'kt',
];

const OTHER_LANGUAGES = [
  'asm',
  'astro',
  'csv',
  'dart',
  'diff',
  'docker',
  'graphql',
  'http',
  'ini',
  'less',
  'log',
  'lua',
  'make',
  'pl',
  'plain',
  'ps1',
  'svelte',
  'toml',
  'uri',
  'vue',
  'xml',
];

export const LIST_LANG = [...POPULAR_LANGUAGES, ...OTHER_LANGUAGES.slice().sort()];

export const MAP_LANGUAGE_LABEL: Record<string, string> = {
  plaintext: 'Plain Text',
  js: 'JavaScript',
  ts: 'TypeScript',
  css: 'CSS',
  html: 'HTML',
  python: 'Python',
  bash: 'Bash',
  asm: 'Assembly',
  astro: 'Astro',
  c: 'C',
  cpp: 'C++',
  cs: 'C#',
  csv: 'CSV',
  dart: 'Dart',
  diff: 'Diff',
  docker: 'Dockerfile',
  go: 'Go',
  graphql: 'GraphQL',
  http: 'HTTP',
  ini: 'INI',
  java: 'Java',
  json: 'JSON',
  jsx: 'JSX',
  kt: 'Kotlin',
  less: 'Less',
  log: 'Log',
  lua: 'Lua',
  make: 'Makefile',
  md: 'Markdown',
  php: 'PHP',
  pl: 'Perl',
  plain: 'Plain Text',
  ps1: 'PowerShell',
  py: 'Python',
  rb: 'Ruby',
  rs: 'Rust',
  scss: 'SCSS',
  sql: 'SQL',
  svelte: 'Svelte',
  swift: 'Swift',
  toml: 'TOML',
  ts_: 'TypeScript',
  tsx: 'TSX',
  uri: 'URI/URL',
  vue: 'Vue.js',
  xml: 'XML',
  yaml: 'YAML',
};

/** Display name of a language id; falls back to the id itself. */
export function languageLabel(value: string): string {
  return MAP_LANGUAGE_LABEL[value] || value;
}
